sudo: false
language: python
cache: pip
python:
  - "2.7"
notifications:
      slack: stockportfolio:cnyIsQVuBjUgajhm9YN9OaI4
before_script:
  - "python manage.py collectstatic --no-input"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 
branches:
  only:
    - master
    - develop
install: "pip install -r requirements.txt"
script: "python manage.py test"
