sudo: false
language: python
cache: pip
python:
  - "2.7"
notifications:
      slack: stockportfolio:cnyIsQVuBjUgajhm9YN9OaI4
branches:
  only:
    - master
    - develop
install: "pip install -r test-requirements.txt"
script: "python manage.py test"
