sudo: false
language: python
cache: pip
python:
- '2.7'
notifications:
  slack: stockportfolio:cnyIsQVuBjUgajhm9YN9OaI4
addons:
  sauce_connect:
    username: "gleisner"
    access_key: $SAUCE
install: pip install -r requirements.txt
script: nosetests
branches:
  only:
    - master
    - develop
