language: python
cache: pip
python:
  - "2.7"
branches:
  only:
    - feature/unittest-setup
notifications:
      slack: stockportfolio:cnyIsQVuBjUgajhm9YN9OaI4

install: "pip install -r requirements.txt"
script: nosetests
