sudo: false
language: python
cache:
  directories:
      - $HOME/virtualenv/python2.7.9
python:
  - "2.7"
services:
  - postgres
notifications:
      slack: stockportfolio:cnyIsQVuBjUgajhm9YN9OaI4
before_script:
  # Check imports
  - isort --check-only --diff --quiet
  - "export DATABASE_URL=postgres://postgres@localhost:5432/spra"
  - psql -c 'create database spra;' -U postgres
  - "python manage.py collectstatic --no-input"
  #- "export DISPLAY=:99.0"
  #- "sh -e /etc/init.d/xvfb start"
  - Xvfb :1 -screen 0 1920x1080x24
  - sleep 3
branches:
  only:
    - master
    - develop
install: "pip install -r requirements.txt"
script: "python manage.py test --keepdb"
