sudo: false
language: python
cache: pip
python:
  - "2.7"
notifications:
      slack: stockportfolio:cnyIsQVuBjUgajhm9YN9OaI4
branches:
  only:
    - master
    - develop
before_install:                                                                                                                                                           
    - sudo apt-get libblas-dev liblapack-dev libatlas-base-dev gfortran
install: "pip install -r requirements.txt"
script: "python manage.py test"
