# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
