# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_portfoliorank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_beta',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_risk',
            field=models.ManyToManyField(to='api.Risk'),
        ),
    ]
