# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_copy_data_to_new_stock_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_stocks',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_quantity',
        ),
    ]
