# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 18:44
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Count


def merge_duplicate_stocks(apps, schema_editor):
    Stock = apps.get_model('api', 'Stock')
    dupes = (Stock.objects.values('stock_ticker')
             .annotate(Count('stock_id')).order_by()
             .filter(stock_id__count__gt=1))
    qs = (Stock.objects.filter(stock_ticker__in=[item['stock_ticker'] for item in dupes])
          .order_by('stock_id'))

    if not qs:
        return

    selected = qs[0]
    for obj in qs.exclude(pk=selected.pk):
        if not obj.stockportfolio_set.all():
            obj.delete()
        else:
            for sp in obj.stockportfolio_set.all():
                sp.stock = selected
                sp.save()
            obj.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_new_stocks_field'),
    ]

    operations = [
    ]
