# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_duplicate_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='risk_date',
            field=models.DateTimeField(),
        ),
    ]
