# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_auto_now_on_risk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_price',
            field=models.ManyToManyField(to='api.Price'),
        ),
    ]
