# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_price_model_for_storing_price_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, db_index=True)),
                ('value', models.IntegerField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Portfolio')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='portfoliovalue',
            unique_together=set([('date', 'portfolio')]),
        ),
    ]
