# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_portfolio_value_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliovalue',
            name='value',
            field=models.FloatField(),
        ),
    ]
